#test
MaxGensMessage: "&8&L[ &e&lORE &8&L] &cDu har max antal gens."
PlacedGenMessage: "&8&L[ &e&lORE &8&L] &aDu placed en gen."
UserDataNotSet: "&8&L[ &e&lORE &8&L] &cKunne ikke finde din userdata... &aopretter userdata"